// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11LSc689dLvv3DXqZ1dhXWHRZJobN4rQ',
    appId: '1:374021905358:web:355cf6640880a96783699f',
    messagingSenderId: '374021905358',
    projectId: 'marwa-d5115',
    authDomain: 'marwa-d5115.firebaseapp.com',
    storageBucket: 'marwa-d5115.appspot.com',
    measurementId: 'G-DYTW1HGPJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJewr2JqRQuxRh-gNRVYMst9vPMCysR4',
    appId: '1:374021905358:android:6cf391832549d9ae83699f',
    messagingSenderId: '374021905358',
    projectId: 'marwa-d5115',
    storageBucket: 'marwa-d5115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLBijo2BZcNGjFRM5WfAXlp5Di1gYcTs',
    appId: '1:374021905358:ios:8420a64aab4ab95c83699f',
    messagingSenderId: '374021905358',
    projectId: 'marwa-d5115',
    storageBucket: 'marwa-d5115.appspot.com',
    iosBundleId: 'com.example.eduprime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLBijo2BZcNGjFRM5WfAXlp5Di1gYcTs',
    appId: '1:374021905358:ios:da98d2fc09a5a4d083699f',
    messagingSenderId: '374021905358',
    projectId: 'marwa-d5115',
    storageBucket: 'marwa-d5115.appspot.com',
    iosBundleId: 'com.example.eduprime.RunnerTests',
  );
}
